feat: 상대 전적 뷰를 구현한다
fc-online-stats-searching/foss pull request #16
Opened 2023-12-02 09:15 UTC by krrong

## 관련 이슈번호
- closed: #15 

<br/>

## 작업 사항
API 명세가 나와있지 않아서 일단 피그마에 나와있는대로 상대 전적 뷰를 구현했습니다.  
그리고 몇 가지 고민이 있어서 의견을 묻고싶어 남기게 되었습니다.  
PR 리뷰 해주시면서 해당 부분에 대한 의견도 남겨주세요 🤠

<br/>

## 기타 사항
### View 변경사항
구현하다 보니 상대전적 뷰에서 승, 패 혹은 승률을 보여주는 것이 애매하다고 생각이 들었습니다.  
그래서 아래 보이는 것처럼 색상으로 누가 더 승률이 높은지 보여주려고 합니다.  
하늘색은 내가 이긴 확률이 높고 붉은색은 상대방이 이긴 확률이 높다 이런식으로요.  
그런데 확 느껴질지는 잘 모르겠습니다.

<img src="https://github.com/fc-online-stats-searching/foss/assets/84285337/49cf4d8e-4cbe-44ac-9b67-a286894fbd7d" width=320>

<br><br>

### 고민 사항
1. 상대 전적에서 누가 더 우세한지를 보여주기 위한 승률을 어떻게 계산할지 고민
- 서버에서 승, 패, 무 를 하나 하나 받아올지
- 도메인에서 UiModel로 변환할 때 승률을 계산해서 만들어줄지
  
어떻게 할까? 생각했을 때 제가 생각한 아주 나이브한 방법입니다. 어떤 방법이 더 나을까에 대해서는 잘 모르겠네요. 더 좋은 방법이 있을까요?

<br><br>

2. `n전 n승 n패`를 보여주기 위해 어떻게 해야할지 고민
- 서버에서 승, 패, 무 를 하나 하나 받아와 `string %d` 로 적절히 변환해서 넣는다.
- 서버에서 `n전 n승 n패` 을 그대로 받아온다. -> 승률 계산이 어려워질 것 같음
  
사실 1번 고민과 연결되는 부분입니다. 승패를 `n전 n승 n패` 이런 식으로 보여주고 싶다면 서버와 데이터를 어떻게 주고 받을지 결정을 해야할 것 같아요.  
그리고 그 과정에서 필요한 고민거리가 1번인 것 같습니다.

<br><br>

3. 검색하지 않은 경우 `사용자 이름을 검색해 주세요.` 라는 문구가 보여야 하는데 어떻게 보여줄 것인가.
- UiState를 활용할 것인가
  
검색을 하면 `사용자 이름을 검색해 주세요.`가 적혀있는 텍스트뷰와 리사이클러뷰의 visibility를 변경하는 방식으로 구현할까 생각하고 있습니다.  
그에 대한 정보를 UiState에 담아야 하는가 생각을 해보았습니다.

2023-12-02 18:53 UTC, boogi-woogi requested changes
정말 고생하셨습니다! 그리고 이런 고민거리들을 남겨주셔서 저 또한 많은 부분에 대해서 다시 생각해볼 수 있었습니다~

### 0. 상대전적 뷰에서 승, 패 혹은 승률을 보여주는 것이 애매하다고 생각이 들었습니다.
-> 아래의 이미지는 op.gg에서 제공하는 특정 유저와의 듀오 전적을 나타냅니다. 개인적인 의견이지만 비슷한 맥락으로 상대 전적 뷰에서 승, 패, 혹은 승률을 보여주는 것도 나쁘지는 않다고 생각합니다! 다만 `특정 유저와의 상대전적에서 앞서고 있다 혹은 밀리고 있다.`라는 것을 확 느껴질 수 있도록하는 방법에 대해서는 디자이너 그리고 팀원들과 조금 더 얘기해보면 좋을 것 같아요! 
![image](https://github.com/fc-online-stats-searching/foss/assets/88770426/0dd4d0ad-12da-4b8a-9a1d-9e27c55887d2)


### 1. 상대 전적에서 누가 더 우세한지를 보여주기 위한 승률을 어떻게 계산할 지 고민
-> 저 역시 비슷한 생각입니다. (서버에서 받아온)data 레이어에서 사용하는 model을 domain으로 변경할 때 계산된 승률을 가지는 domain Model을 만들고 이를 ui에서 보여 줄 수 있는 형식으로 uiModel로 mapping시키는 방법이 가장 일반적이고 좋다고 생각합니다!

### 2. n전 n승 n패를 보여주기 위한 고민
-> 서버로 부터는 승, 패, 무를 숫자 형식으로 받아오는 것이 적합하다고 생각합니다. 그리고 uiModel에서도 승, 패, 무에 관한 값을 int 타입(숫자 타입)으로 가지고 화면에 표현할 방식을 string.xml로 만들어 표시하면 된다고 생각합니다! 

불필요한 로직 없이 화면에 보여주기 위한 데이터를 가진다면 무엇이든지 uiModel이 될 수 있다고 생각하고, 꼭 String형식으로 바로 화면에 표시할 수 있는 상태로 존재하지는 않아도 된다고 생각합니다. 

### 3.  검색하지 않은 경우 사용자 이름을 검색해 주세요. 라는 문구가 보여야 하는데 어떻게 보여줄 것인가.
-> 제시해주신 방법도 좋을 것 같고 구현할 수 있는 방법이 정말 많다고 생각합니다! 원하시는대로 구현하고 함께 개선해나가도 좋을 것 같습니다ㅎㅎ

2023-12-02 18:53 UTC, boogi-woogi commented on android/app/src/main/res/layout/item_relative_stats.xml
> +    </data>
[P3]
저 또한 현재 데이터 바인딩을 사용하면서 구현을 하고 있습니다. 

고민이 되는 부분이 있는데 데이터 바인딩을 사용하는 경우 읽는 사람의 입장에서 코드가 너무 파편화된다는 느낌을 지울 수가 없는 것 같아요. 다 같이 논의해봐야 할 문제이지만 viewBinding만 사용하는 것에 대해서 어떻게 생각하시는지 궁금합니다!

2023-12-02 18:53 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsVIewHolder.kt
> +class RelativeStatsVIewHolder(
[P1]
`RelativeStatsViewHolder`로 수정해주시면 감사하겠습니다ㅎㅎ

2023-12-02 18:53 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsVIewHolder.kt
> +    private val binding = ItemRelativeStatsBinding.bind(itemView)
[P5]
개인적으로 생성자 안의 코드는 읽기 편하는 것이 좋다고 생각하고 또 스스로 일하는 객체를 만들기 위해서 저는 [ViewHolder의 팩토리 메서드](https://github.com/fc-online-stats-searching/foss/blob/android/android/app/src/main/java/com/foss/foss/feature/statsearching/legacy/MatchResultViewHolder.kt)로 생성하는 것을 선호하고는 합니다.

물론 이 부분은 정말 방법의 차이 혹은 취향 차이라고 생각합니다~

2023-12-04 16:41 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsVIewHolder.kt
> +class RelativeStatsVIewHolder(
반영했습니다ㅎㅎ

2023-12-04 16:46 UTC, krrong commented on android/app/src/main/res/layout/item_relative_stats.xml
> +    </data>
이전에 이야기한 대로 viewBinding으로 변경했습니다!

2023-12-04 17:08 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsVIewHolder.kt
> +    private val binding = ItemRelativeStatsBinding.bind(itemView)
이렇게 구현할 수도 있네요..!
데이터 바인딩을 사용한다는 것을 좀 더 명시적으로 알려주는 것 같고 생성자 안의 코드가 간단해져서 이 방법이 더 마음에 드는 것 같습니다!

다만 이것이 스스로 일하는 객체를 위해서 한 것인가?에 대한 부분은 아직 잘 와닿지 않네욤🥲

메서드 명이 `valueOf`보다는 `from`이 객체를 반환해준다는 느낌을 더 받아서 그렇게 작성했는데 어떻게 생각하나요?
추가로 동반 객체에 있는 메서드만을 이용하여 인스턴스를 반환해줄 것이기 때문에 주생성자를 private하게 해두어야 할 것 같다는 생각도 듭니다!

2023-12-04 17:11 UTC, krrong commented
아직 API 명세가 나오지 않은 시점이어서 일단 고민거리에 대한 내용은 코드에 담지 않았습니다! 
이 고민거리들을 기능을 개발하면서 가지고 가고, 다음 사람에게 리팩터링 할 수 있도록 전달하도록 할게요 :)

2023-12-04 17:22 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsVIewHolder.kt
> +    private val binding = ItemRelativeStatsBinding.bind(itemView)
말씀해주신 것처럼 private constructor를 이용하는 것이 적합하다고 생각합니다👍 

특정 객체를 만들 때 **팩토리 메서드 패턴**을 이용하는 것은 외부에서는 이 객체가 생성되는 과정에 크게 관여하지 않고 해당 서브 클래스 내부에서 스스로 객체 생성을 결정하도록 만든다고 생각합니다. 때문에 저는 다음과 같이 ViewHolder를 생성할 때 팩토리 메서드를 이용하는 것도 일종의 `스스로 일하는 객체`를 만드는 것이라고 생각합니다!

물론 제시해주신 방법도 스스로 일하는 객체를 만든다고 생각하지만 방법의 차이라고도 볼 수 있을 것 같아요! 다만 저는 이런 경우에 팩토리 메서드를 주로 이용한다는 것을 말씀드리고 싶었습니다ㅎㅎ

2023-12-05 02:19 UTC, yoonhyeokCho approved these changes
### View 변경사항
개인적이지만 저는 수정한 View 처럼 붉은색과 푸른색만으로도 와닿을 것 같습니다.
다른 사람들 의견은 어떤지 모르겠네요... 

### 고민 1,2
불필요하게 승 패 무를 각각 받아오는 것보다는 n전 n승 n패를 한번에 받아서  도메인 레이어에서 승률 계산 로직을 처리하고 uiModel로 전달하는 방법이 좋다고 생각합니다 !

### 고민 3
제시해주신 것과 같이 검색 상태에 대한 정보를 UiState 담아서 처리하는 것이 좋아보입니다.

2023-12-05 02:19 UTC, yoonhyeokCho commented on android/app/src/main/res/layout/item_relative_stats.xml
> +            android:textStyle="bold"
[P5]
유저 닉네임에 대한 텍스트 스타일이 최근 전적 검색에서도 동일하게 사용 되는데, 따로 스타일 리소스로 정의를 해놓고 사용하는 것이 어떨까요 ?

2023-12-05 07:47 UTC, boogi-woogi approved these changes
고생하셨습니다~ 머지 시키겠습니다~

2023-12-05 07:47 UTC, merged

2023-12-05 08:22 UTC, krrong commented on android/app/src/main/res/layout/item_relative_stats.xml
> +            android:textStyle="bold"
그렇게 진행해도 좋을 것 같아요 :)