feat: 최근 전적을 조회할 수 있는 기능을 구현한다.
fc-online-stats-searching/foss pull request #17
Opened 2023-12-04 16:05 UTC by boogi-woogi

## 관련 이슈번호
- #11 

## 작업 사항
최근 전적을 조회할 수 있는 기능을 구현

## 기타 사항
### 현재 승리, 패배, 무승부를 나타내는 WinDrawLose라는 domain model을 uiModel에서는 아래의 사진과 같은 형식으로 구현했습니다.
(StringRes를 가지는 enum class)
![image](https://github.com/fc-online-stats-searching/foss/assets/88770426/dbf1878d-ae24-49be-b385-37ace1f3f8ca)

그 이유는 다음과 같습니다. 먼저 경기 결과를 나타내는 리사이클러뷰의 아이템 내부에 존재하는 text, side에 위치한 view, 등 승리, 무승부, 패배에 따라서 색깔이 바뀌는 요소들이 많이 존재합니다. 만약 uiModel에서 이것들을 그냥 string타입의 property로 가진다면 모든 분기를 문자열 비교로 결정해야하기 때문에 코드의 안정성이 떨어진다고 생각했고 enum으로 구현했습니다.

또한 다국어 지원을 한다고 했을때 영향을 받을 수 있는 문자열들을 지금과 같은 형태로 StringRes를 가지게 되면 큰 변동 사항 없이 구현할 수 있다고 생각합니다.

### UiModel에서 android 의존성(`@StringRes`)이 있는 것이 적절할까?
이 부분도 생각해보았지만 Domain Model이 아닌 UiModel이기 때문에 특정 플랫폼에 의존되는 형태는 크게 문제될 것이 없다고 생각합니다.

더 좋은 방법이 생각나시면 말씀해주세요! 
![image](https://github.com/fc-online-stats-searching/foss/assets/88770426/21f45a15-8961-4d74-99f6-c230013d6a97)
---
### 만약 모든 경기의 내용과 경기 타입이 같은 경우 DiffUtil에서의 구분
만약 경기 내용이 같고 경기 타입, 플레이한 유저들이 모두 같을 때 `areItemsTheSame()` 여기서 어떻게 구분해야할까요? 지금 당장 필요한 부분은 아니지만 현재 어떻게 해야할 지 좋은 아이디어가 잘 떠오르지 않네요ㅠㅠ
![image](https://github.com/fc-online-stats-searching/foss/assets/88770426/e1f994b2-3457-41d1-9f43-b08e494b9687)
---
### Glide 오류
현재 MOM 선수의 사진이 띄워지지 않는 오류가 있는데 이 부분도 함께 해결하면 좋을듯합니다.

2023-12-05 06:21 UTC, krrong requested changes
고생했습니다!! 몇 가지 궁금한 점 위주로 코멘트 달았으니 확인 부탁드릴게요 :)

> WinDrawLose라는 domain model을 uiModel에서는 아래의 사진과 같은 형식으로 구현했습니다.

괜찮은 방법이라고 생각합니다!

> UiModel에서 android 의존성(@StringRes)이 있는 것이 적절할까?

저도 제시해준 이유와 같이 생각해서 괜찮다고 생각합니다.

> 만약 모든 경기의 내용과 경기 타입이 같은 경우 DiffUtil에서의 구분

이러한 경우가 있을 수 있겠네요. 그런데 이름을 재검색 하는 경우는 어댑터에 데이터를 새로 넣어주면 되기 때문에 문제가 없을 것 같은데  아마 새로 고침을 하게 되면 문제가 생기려나요?  
피파 API를 살펴보니 경기의 날짜를 받아올 때 2019-05-13T18:03:10 이와 같이 받아올 수 있더군요. 좀 더 상세한 정보를 받아오면 비교가 가능하지 않을까 생각이 드네요!

> 현재 MOM 선수의 사진이 띄워지지 않는 오류가 있는데 이 부분도 함께 해결하면 좋을듯합니다.

저는 잘.. 나옵니다..!ㅋㅋ

2023-12-05 06:21 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/MatchViewHolder.kt
> +            this.match = match
P[3]  
이미지 바인딩 때문에 남겨둔 것일까요?

2023-12-05 06:21 UTC, krrong commented on android/app/src/main/res/layout/item_match.xml
> +            android:text="@{match.otherSideNickname}"
P[3]  
상대방의 닉네임을 데이터바인딩으로 연결해준 것은 의도한 것일까요?

2023-12-05 06:21 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
>      }
P[4]  
요렇게 구성한 이유는 무엇인가요?

2023-12-05 06:21 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
> +        }
P[2]  
현재 로고를 클릭하면 경기 결과가 나오도록 구현한 것은 임시로 진행한 것이겠죠?  
검색을 어떻게 유도할지 고민해보면 좋겠네요!

문득 든 생각인데, 최근 검색 기록을 데이터베이스에 저장해서 사용자에게 보여줘도 좋겠다는 생각도 들었습니다!

2023-12-05 07:41 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/RecentMatchesFragment.kt
> +class RecentMatchesFragment : DiFragment() {
이 부분을 조금 더 얘기해봐야 할 것 같아요. 구현할 때 repository 네이밍을 생각하다보니 결국 repository에서는 전적이라는 개념보다는 최근 경기에 대한 결과를 제공한다고 생각해서 이렇게 변경했는데 내일 회의할 때 한번 얘기해보시죠!

2023-12-05 07:41 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/MatchViewHolder.kt
> +            this.match = match
넵~ 데이터 바인딩 부분 모두 뷰바인딩으로 변경하겠습니다~~

2023-12-05 07:43 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
>      }
이렇게 구성한 이유라가 혹시 .also를 이용한 이유를 말씀하시는건가요?? 아니면 데이터 바인딩을 연결한 것을 말씀하시는 것일까요??

2023-12-05 07:46 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
> +        }
넵! 맞습니다 현재 버튼이 없어서 임시로 로고를 클릭하면 검색이 되도록 구현해놨습니다!

말씀해주신 기능이 사용자들 입장에서 충분히 사용할만한 기능이라고 생각합니다:+1:

2023-12-05 14:39 UTC, yoonhyeokCho approved these changes
> ### UiModel에서 android 의존성(@StringRes)이 있는 것이 적절할까?
UI 모델에서는 리소스 및 특정 플랫폼 의존성을 허용하며, 이것이 관용적인 방법이라고 하네요 ! 

> ### 만약 모든 경기의 내용과 경기 타입이 같은 경우 DiffUtil에서의 구분]
당장 생각나는 방법은 딱히 없네요. API 작성이 완료 되면 그때 한번 얘기해보죠,,, 

>### Glide 오류
임시데이터로 넣은 값 (https://fco.dn.nexoncdn.co.kr/live/externalAssets/common/players/p1.png) 으로 테스트 해봤는데 문제 없이 잘 나옵니다.

2023-12-06 06:06 UTC, boogi-woogi commented on android/app/src/main/res/layout/item_match.xml
> +            android:text="@{match.otherSideNickname}"
현재 뷰바인딩으로 모두 교체 완료했습니다!

2023-12-06 11:46 UTC, yoonhyeokCho approved these changes
고생하셨습니다 !

2023-12-06 11:46 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/MatchViewHolder.kt
> +    }
[P2]

특정 선수의 이미지가 존재하지 않을 수도 있다고 하는데, 이미지 URL이 null값일 경우도 처리해줘야 할 것 같습니다.

load할 url이 null인 경우 등 비어있을 때 보여줄 이미지를 설정하는 `fallback()` 메서드가 있습니다.

2023-12-06 11:46 UTC, merged