feat: 상대 전적을 조회할 수 있는 기능을 구현한다.
fc-online-stats-searching/foss pull request #24
Opened 2023-12-11 12:03 UTC by boogi-woogi

## 관련 이슈번호
- #23 

## 작업 사항
가짜 데이터를 이용해 상대 전적을 조회할 수 있는 기능을 구현
viewModel 테스트 코드 작성

## 기타 사항
<br/>

2023-12-12 16:18 UTC, krrong requested changes
고생했습니다!

> 테스트 코드에서 목 객체의 행동을 지정하는 부분과 지정된 행동을 유발하는 viewModel 함수를 가독성 개선을 위해 한글로 만들어보았습니다. 이 방법에 대해서는 어떻게 생각하시는지 궁금합니다.

코멘트로도 남겼지만 저는 마음에 듭니다!

조금씩 구색을 갖춰가는 것 같아 좋은 것 같습니다!
남긴 코멘트 확인해주세요!

2023-12-12 16:18 UTC, krrong commented on android/app/src/test/java/RelativeStatsViewModelTest.kt
> +        `상대전적 기록 요청을 하면`()
[P3]
어색하긴 하지만 좋은 것 같네요 :0

2023-12-12 16:18 UTC, krrong commented on android/app/src/test/java/RelativeStatsViewModelTest.kt
> +            val actual = awaitItem()
[P4]
`awaitItem`을 통해 event의 값을 받아올 때까지 기다리는 건가요?

2023-12-12 16:18 UTC, krrong commented on android/domain/src/main/java/com/foss/foss/model/legacy/Score.kt
> + */
[P3]
어떤 변수명이 더 맘에드는지 궁금합니다.

2023-12-14 11:16 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsAdapter.kt
> +    ListAdapter<RelativeStatUiModel, RelativeStatsViewHolder>(RelativeStatDiffUtilCallBack()) {
아이템이 바뀌지 않는 상황에서는 일반적인 Recycler.Adapter를 사용해도 무방하다고 생각합니다.

하지만 현재 구현하고 있는 view에서는 결국 검색에 따라서 recyclerView의 아이템들이 계속해서 변경되기 때문에 ListAdapter를 사용하지 않을 이유가 없다고 생각했습니다!

2023-12-14 11:16 UTC, boogi-woogi commented on android/app/src/test/java/RelativeStatsViewModelTest.kt
> +        `상대전적 기록 요청을 하면`()
이것저것 시도해보는 것도 재밌네요ㅎㅎ

2023-12-14 11:18 UTC, boogi-woogi commented on android/app/src/test/java/RelativeStatsViewModelTest.kt
> +            val actual = awaitItem()
넵 맞습니다!

자세한 내용은 [링크](https://github.com/cashapp/turbine?tab=readme-ov-file#usage)참고해보시면 좋을 것 같아요!

2023-12-14 11:20 UTC, boogi-woogi commented on android/domain/src/main/java/com/foss/foss/model/legacy/Score.kt
> + */
goal과 conceded가 의미적으론 더 적합하다고 생각합니다. 그런데 conceded라는 것을 개발자가 보았을 때 쉽게 이해할 수 있을지가 고민이네요ㅜㅜ

2023-12-14 11:24 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsFragment.kt
> +        }
LifecycleOwner와 널리 쓰일 수 있는 타입에 대해서 확장함수를 만드는 것에 대한 위험성때문에 만들지 않았는데 크롱이 제시해주신 함수명이 정말 직관적이라 저희끼리 합의만 된다면 코드 양을 줄이는 좋은 방법이라고 생각합니다.

2023-12-14 11:54 UTC, yoonhyeokCho approved these changes
## 고생하셨습니다 !

> ### StateFlow와 SharedFlow를 사용했습니다.
SharedFlow를 테스트 하기위해 turbine이라는 라이브러리 종속성을 추가했습니다.
사용법은 완전히 숙지한 것이 아니라 추가적인 학습이 필요해보입니다.

잘 작성된 것 같습니다 !! 
저도 해당 부분에 대해서 공부하는 중입니다 ㅎㅎ

> ### 테스트 코드에서 목 객체의 행동을 지정하는 부분과 지정된 행동을 유발하는 viewModel 함수를 가독성 개선을 위해 한글로 만들어보았습니다. 이 방법에 대해서는 어떻게 생각하시는지 궁금합니다.

확실히 한글로 작성하니까 가독성이 좋긴 하네요. 문제 없을 것 같습니다 !

2023-12-14 11:54 UTC, merged