feat: 자세한 상대 전적을 조회하는 기능을 구현한다.
fc-online-stats-searching/foss pull request #26
Opened 2023-12-16 13:59 UTC by krrong

## 관련 이슈번호
- closed: #25 
<br/>

## 작업 사항
### RelativeDetailStatsFragment
상대 중 한 명을 클릭하면 더 자세한 상대 전적을 볼 수 있는 프래그먼트를 오픈합니다.  
`addToBackStack`을 통해 뒤로가기를 누르면 이전 프래그먼트가 보이도록 했습니다.

### ViewModel 공유
RelativeDetailStatsFragment와 RelativeStatsFragment가 액티비티에 있는 뷰모델을 공유해서 사용하도록 구현했는데 어떻게 생각하시는지 궁금합니다.

### DataBinding
EditText에 있는 값을 양방향 데이터 바인딩을 통해 사용하기 위해 추가했는데 어떻게 생각하시나요? 

<br/>

## 기타 사항
<br/>

2023-12-18 07:05 UTC, yoonhyeokCho approved these changes
고생하셨습니다 !

### ViewModel 공유
두 프래그먼트에서 필요로하는 데이터의 종류가 같아서  viewModel 을 공유하는 방법 괜챃은 것 같아요. 
### DataBinding
직관적이고 간결해서 저도 선호하는 방법입니다 ! 좋은 것 같아요

2023-12-18 07:08 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/detail/RelativeDetailStatsFragment.kt
> +        }
LifeCycleUtil.kt 파일에 다음과 같이 만들어둔 함수입니다!
```kotlin
fun LifecycleOwner.repeatOnStarted(block: suspend CoroutineScope.() -> Unit) {
    lifecycleScope.launch {
        lifecycle.repeatOnLifecycle(Lifecycle.State.STARTED, block)
    }
}
```
일반적으로 이런 방식으로 많이 사용하더라구요!

2023-12-18 12:04 UTC, boogi-woogi requested changes
정말 정말 고생하셨습니다ㅎㅎ

상대전적 세부 화면 뷰를 구현하는 것만 해도 양이 적지 않네요 ㄷㄷ

그리고 한가지 궁금한 점은 이번 PR에는 현재 구현해주신 부분까지 할 계획이신지 아니면 uiState까지 적용해보실 생각이 있는지 궁금합니다! 

### 뷰모델 공유

현재 구현해주신 방법이 합리적이라고 생각합니다!!

### dataBinding

아래 리뷰에 의견을 남겨두었습니다!

2023-12-19 08:37 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +        MutableStateFlow(emptyList())
![image](https://github.com/fc-online-stats-searching/foss/assets/84285337/12eeaf65-3102-4b09-b250-72b7ab4dcdbd)

다른 점은 없지만 명시적으로 알려준다고 생각해서 바꿔봤습니다.  
`emptyList()` 를 사용하면 여기에는 빈 리스트가 들어가는 것이겠구나라고 명확하게 이해할 수 있을 것이라고 생각해요.  
더불어 `emptyList()`에 인자를 넣어주는 실수를 해도 문제가 없지 않을까하는 생각도 드네요.

2023-12-19 08:39 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
>      }
네 맞습니다.

2023-12-19 08:40 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/RecentMatchesFragment.kt
> +
UIState를 사용하도록 변경하면 뷰에서는 UIState 하나만을 관찰하고 있으면 되기 때문에 Loading 상태가 아닌 경우(어떤 상태를 두느냐는 더 이야기 해보면 좋겠지만) `사용자 이름을 검색해주세요.` 문구의 visibility를 조절하면 될 것이라고 생각합니다!

2023-12-19 08:50 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +    }
그 부분에 대해 곰곰히 생각해봤는데 제 생각은 다음과 같습니다.  
상대 전적을 보여주는 뷰에서는 어떤 유저와의 승패나 골득실을 보여주지만 디테일 뷰로 들어가면 결국 최근 전적을 보여주는 뷰의 데이터와 동일하다고 생각합니다.  
그러면 이 데이터는 `MatchRepository`에서 가져오고, `MatchRepository`가 가지고 있는 함수명에는 Relative는 없는 것이 나을 것 같다고 생각하는데 어떻게 생각하시나요?  

그래서 일단 뷰모델의 함수명만 변경했습니다!

2023-12-19 08:55 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +    private var _opponentName = ""
> ViewModel에서 현재 editText에 대한 변경사항을 계속해서 받는 것이 어찌보면 view에 대한 의존성이 있다고도 느껴집니다

그렇게 생각도 되긴 하네요.

사실 이렇게 구현하게 된 계기는 다음과 같습니다.  

미션을 진행하면서 뷰의 데이터를 그대로 긁어와 사용하는 것은 좋지 않다 라고 레아가 코멘트를 남겨주셨거든요. 그래서 이를 피하기 위한 다른 방법을 생각해보았을 때 양방향 데이터 바인딩을 사용하는 것이 좋겠다는 생각을 했습니다. 그래서 dataBinding을 사용하여 구현했습니다.  

다시 생각해보았을 때 뷰의 데이터를 긁어와 그대로 사용하는 것이 아니라 긁어온 데이터를 포장해서 사용하면 어떻게 하든 문제가 없을 것이라고 생각이 들었습니다.   
그럼 데이터 바인딩을 삭제하고 원시값을 포장해서 사용하도록 변경해도 괜찮을까요?  


아니면 더 좋은 방법이 있다면 추천해주셔도 됩니다 :)

2023-12-19 08:58 UTC, krrong commented on android/app/src/main/java/com/foss/foss/util/OnChangeVisibilityListener.kt
> +}
추상화한 이유는 액티비티에서 이 메서드를 구현해야 한다! 라고 명시적으로 알려주기 위해서였습니다. 해당 인터페이스를 구현하도록 해서 액티비티가 어떤 책임을 가지고 있는지 조금 더 쉽게 파악할 수 있지 않을까 라고 생각했어요.

추상화하지 않고 액티비티에서 바로 구현해도 괜찮을 것 같다는 생각을 하기도 합니다. ㅋㅋ

2023-12-19 08:59 UTC, krrong commented on android/app/src/main/res/layout/fragment_recent_matches.xml
> +        android:text="@string/relative_info"
String resource의 아이디를 변경해달라는 것으로 이해했는데 잘 이해한 것이 맞을까요?!

2023-12-19 09:01 UTC, krrong commented
> 그리고 한가지 궁금한 점은 이번 PR에는 현재 구현해주신 부분까지 할 계획이신지 아니면 uiState까지 적용해보실 생각이 있는지 궁금합니다!

UIState는 나중에 리팩터링 해보아도 괜찮지 않을까 생각합니다!  
제가 아닌 다른 사람이어도 괜찮구요 :)

2023-12-20 04:17 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +        MutableStateFlow(emptyList())
오호 감사합니다~

2023-12-20 04:18 UTC, boogi-woogi commented on android/app/src/main/res/layout/fragment_recent_matches.xml
> +        android:text="@string/relative_info"
넵 맞습니다!

2023-12-20 04:19 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +    private var _opponentName = ""
넵 좋습니다!

>>뷰의 데이터를 그대로 긁어와 사용하는 것은 좋지 않다.
혹시 이것에 대한 이유를 알 수 있을까요??

2023-12-20 04:24 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +    }
말씀해주신 의견과 함께 현재 `MatchRepository`에서 가져오는 형태라면 지금 작성해주신 함수명이 적절한 것 같아요ㅎㅎ

2023-12-20 05:01 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +    private var _opponentName = ""
EditText에 어떤 데이터가 들어갈지 모르기 때문에 피파에서 지원하지 않는 형태의 닉네임(길이가 매우 긴 or 특수문자가 포함된)이 들어오면 문제가 발생할 수도 있다고 생각합니다. 넥슨 API에서 해당 부분에 대한 것도 처리를 해주었겠지만, 원시값 포장을 하면 불필요한 API 요청 자체도 줄일 수 있다고 생각합니다.  

아래는 레아가 남겨주신 코멘트입니다. 참고해도 좋을 것 같아요.
https://github.com/woowacourse/android-shopping-order/pull/43#discussion_r1218345034

2023-12-20 05:09 UTC, krrong commented on android/app/src/main/res/layout/fragment_recent_matches.xml
> +        android:text="@string/relative_info"
`search_hint_user_name`로 변경했고, 텍스트 뷰 아이디도 모두 변경했습니다 :)

2023-12-20 05:13 UTC, merged