feat: 나의 최근 전적에 UIState를 적용한다.
fc-online-stats-searching/foss pull request #31
Opened 2023-12-22 07:46 UTC by yoonhyeokCho

## 관련 이슈번호
<br/>

#28 

## 작업 사항
<br/>

- 최근전적 검색에 UiState 적용
- 최근전적 ViewModel LiveData -> Flow 변경
- 최근전적 ViewModel 테스트코드 작성
## 기타 사항
<br/>

###  1. java.lang.RuntimeException: Cannot create an instance of class com.foss.foss.feature.statsearching.recent.RecentMatchesViewModel 오류
LiveData -> Flow 로 바꾼 후 HomeActivity에서 RecentMatchesViewModel인스턴스를 생성하지 않았다는 오류가 계속 발생하여 MatchType은 Flow로 변경하지 않고, 이를 HomeActivity에서 Observer하는 코드를 임시로 추가했습니다.
<img width="1106" alt="292394155-02f3b2fa-0440-4404-b7f9-7d259fa5f764" src="https://github.com/fc-online-stats-searching/foss/assets/90389363/aef71948-a7d4-4b2b-8414-f06a8d71c2d9">

### 2. 2. Event 처리 관련
2차 스프린트 작업 사항에 실패 Event처리를 따로 하기로 했어서 Event처리를 위해 따로 RecentMatchesEvent 를 만들었습니다. 그리고 fetchMatches()에 실패했을 때 UiState error 처리, 이벤트 Failed 처리 모두 하고 있는데, 두 개 다 만들 필요가 있나요 ?? 어차피 UiState error일때랑 이벤트 failed할 때가 fetchMatches()실패 했을 때로 동일한 이유라,, 그냥 UiState.error 일때 오류 핸들을 하면 되지 않을까 라는 생각이 드네요
위 질문에서 오류 Event 처리를 따로 해야 한다고 하면 RelativeStatesEvent 와 RecentMatchEvent 모두 실패 이벤트 처리를 위해 만든거라 동일한 역할을 하고있으니 따로 두지말고 합치는건 어떨까요 ??

2023-12-23 06:27 UTC, krrong requested changes
고생하셨습니다!  

저도 UiState를 도입하면 RecentMatchesEvent 인터페이스는 필요하지 않다고 생각하긴 합니다.  
다만 UiState는 하나의 뷰에 하나씩 존재하고, 해당 UiState가 Success, Loading, Fail의 상태를(필요하다면 더 많은 상태를) 갖도록 구현하는 것이 낫지 않을까 생각합니다.

2023-12-23 06:27 UTC, krrong commented on android/app/src/main/java/com/foss/foss/util/UiState.kt
> +sealed class UiState<out T>(val _data: T?) {
[P3]  
UiState를 이처럼 만든 이유는 여러 화면에서 함께 사용하기 위함인 것 같습니다.  
그렇다면 A 액티비티에서는 [List<String>, String, Int]의 데이터가, B 액티비티에서는 [List<String>, List<Int>]의 데이터가 필요하게 되면 어떻게 사용할 수 있을까요?

2023-12-23 06:27 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/RecentMatchesFragment.kt
> +
[P4]  
이 부분은 왜 주석인가요??

2023-12-23 06:27 UTC, krrong commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +
[P3]  
이 부분도 다른 테스트 파일처럼 한글 함수로 분리해도 좋겠네요 :)

2023-12-23 06:27 UTC, krrong commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +
[P2]  
개행이 많이 되어있어 무엇을 비교하는지 한 눈에 보기 어려웠습니다.  
테스트 코드의 가독성을 위해 다음과 같이 수정해보는 것은 어떤가요? 

```kotlin
val expected = recentMatchesViewModel.uiState.value
val actual = UiState.Success(matches.map { it.toUiModel() })

assertEquals(expected, actual)
```

2023-12-23 09:16 UTC, boogi-woogi requested changes
모킹을 이용해 처음으로 테스트 코드를 작성하신 것으로 알고 있는데 정말 고생하셨습니다!!

> 2. Event 처리 관련
주관적인 의견이지만 uiState라는 것은 말 그대로 현재 ui의 보여질 데이터들을 가지고 있는 화면이라고 생각합니다. 

uiState를 통해 오류에 대한 이벤트를 처리하는 것은 uiState가 화면에 보여질 데이터 + 추가적인 이벤트 처리 모두를 담당하게 되면서 uiState를 비대해지는 문제가 발생할 수도 있다고 생각합니다. 현재처럼 이벤트만을 처리하는 sealed interface 혹은 sealed class로 분기를 처리해서 이벤트를 처리하는 것이 더 좋은 방법이라고 생각합니다!

2023-12-23 09:16 UTC, boogi-woogi commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +
[P3]
현재 given, when, then형식으로 잘 작성해주셨는데 실제 테스트 함수의 결과 값 actual과 기대하는 값 expected라는 변수명을 이용해 가독성을 조금 더 개선해주시면 좋을 것 같아요!

2023-12-23 09:16 UTC, boogi-woogi commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +            )
[P3]
이런 부분은 Fixture라고하는 테스트에서의 고정된 객체값으로 설정해보면 좋을 것 같아요. 

함수의 동작을 테스트하는데 있어서 이 Match의 property들이 어떤 데이터를 갖고 있는지에 대한 것은 중요한 관심사가 아니라고 생각합니다!

참고 코드(다음과 같이 특정 객체들을 반환하는 fixture 클래스를 object로 만들어 사용하고는 합니다.): https://github.com/woowacourse-teams/2023-diggin-room/blob/android/android/app/src/test/java/com/digginroom/digginroom/fixture/RoomFixture.kt


참고 자료: https://zorba91.tistory.com/304

2023-12-26 08:35 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/util/UiState.kt
> +sealed class UiState<out T>(val _data: T?) {
우선은 최근 경기를 받아온 정보만 처리를 해서 단일 데이터만 받아올 수 있게 해놓았는데 그렇게 된다면 화면 마다 따로 두는 것이 맞을 것 같네요,, ! 
UiState를 각 화면마다 따로 두는 것이 좋을 것 같습니다.

2023-12-26 08:36 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/RecentMatchesFragment.kt
> +
RecentMatchesViewModel의 MatchType을 Flow로 변경하는 과정에서 작성했던 코드인데, 기타사항 1의 오류때문에 다시 LiveData로 바꾸면서 우선은 주석 처리 해두었습니다.

2023-12-26 08:37 UTC, yoonhyeokCho commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +
넵 코드 가독성을 위해서 그게 좋을 것 같네요 ! 
수정하겠습니다.

2023-12-26 08:38 UTC, yoonhyeokCho commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +
처음에 그렇게 해두었다가 저게 더 가독성이 좋을까 싶어 수정을 했는데,,, 다른 사람이 봤을 때는 가독성이 안 좋을 수도 있겠군요 !! 
수정하겠습니다.

2023-12-26 08:39 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/util/UiState.kt
> +}
넵 크롱님 의견과 동일하군요 ! 
각 화면마다 UiState를 따로 두는 것이 좋을 것 같네요. 
수정하겠습니다

2023-12-26 08:40 UTC, yoonhyeokCho commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +
네 좀 더 가독성있게 수정하도록 하겠습니다. 의견 감사합니다 !

2023-12-26 08:42 UTC, yoonhyeokCho commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +            )
그런 방법이 있네요 ! 다음에 고정된 객체가 필요하다면 참고하도록 하겠습니다.

근데 말씀하신 것 처럼 현재 테스트코드 동작에서 어떤 값들을 가지는 지는 관심사가 아니라서 우선은 삭제하도록 하겠습니다 !

2023-12-27 11:33 UTC, boogi-woogi requested changes
고생하셨습니다! 코멘트 남겼으니 한번 확인해주시면 감사하겠습니다~

2023-12-27 11:33 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/util/UiState.kt
> +}
[P2]
각각의 uiState는 util성 파일이 아닌것처럼 보입니다! uiState에 해당되는 feature 패키지로 이동 시키는게 좋을 것 같아요!

Loading, Error, Success에 data가 공통적으로 필요하지 않다면 sealed interface를 이용해 Success에만 프로퍼티가 존재하도록 만들 수 있을 것 같아요.

그리고 여기서 제네릭 타입을 사용하신 이유가 있으실까요?

2023-12-27 11:33 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/RecentMatchesViewModel.kt
> +        }
[P4]
현재 event로 Failed라는 이벤트를 emit하고 있습니다. uiState에도 비슷한 성격으로 보이는 Error가 존재하는데 어떠한 처리를 추가적으로 하실 계획인가요?

2023-12-27 11:33 UTC, boogi-woogi commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +    }
[P3]
사실 제가 의도한 바는 다음과 같이 matches의 값이 어떠한 값이 되어도 상관이 없기 때문에 이를 Fixture로 설정해 외부에서 보았을 때는 그냥 어떠한 List<Match>의 값이 있구라 라는 것을 표현하는 것을 의미했습니다.

```suggestion
    @Test
    fun `경기정보 가져오기 성공 시 UiState를 Success로 업데이트한다`() {
        // given
        val nickname = "사용자 이름"
        val matches: List<Match> = MatchFixture.matches // 어떠한 고정값
        
        coEvery {
            matchRepository.fetchMatches(nickname)
        } returns Result.success(matches)

        // when
        `최근전적 기록을 요청하면`(nickname)
        val actual = recentMatchesViewModel.uiState.value

        // then
        val expected = RecentMatchesUiState.Success(matches)
        assertEquals(expected, actual)
    }
```

2023-12-28 07:12 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/util/UiState.kt
> +}
앞전에 sealed interface로 만드는 것이 어떤지 코멘트 남겨주신 것이 이 의미였군요 ! 제가 잘못 이해하고 있었던 것 같아요. 
Loading과 Error시에는 data가 필요없으니, 제안해 주신 대로 sealed interface로 만들고, Success에만 프로퍼티 존재하도록 만드는 것이 좋을 것 같습니다.

딱히 이유를 두고 한 것은 아니지만, 타입을 명확하게 명시하는게 좋을까요 ??

2023-12-28 07:15 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/statsearching/recent/RecentMatchesViewModel.kt
> +        }
제가 같이 의논해 보려던 것이 이에 관한 것입니다.
2차 스프린트 기간 중 오류 이벤트에 관해서 SharedFlow로 처리를 하자고 계획을 했어서 우선은 만들어 두었는데, 현재 UiState에도 Error에 대한 처리를 하고 있고 event에서도 같은 처리를 하고 있어서 굳이 두개를 둘 필요가 있을까 하는 고민입니다.

좋은 의견이 있을까요 ?

2023-12-28 07:20 UTC, yoonhyeokCho commented on android/app/src/test/java/RecentMatchesViewModelTest.kt
> +    }
네. 근데 말씀하신 것처럼 Match의 값이 어떤 것이 들어가든 상관없는 테스트코드라 빈 리스트를 만들어서 처리했는데, 굳이 따로 Fixture를 만들어서 관리할 필요가 있나요 ? 

이 부분에 대해서 잘 몰라서 여쭤봅니다 !

2023-12-29 06:30 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/util/UiState.kt
> +}
어짜피 home화면 그리고 RecentMatches에서만 사용되는 uiState라면 굳이 제네릭을 사용할  필요가 없어보입니다!

2023-12-30 07:23 UTC, krrong approved these changes
고생하셨습니다!  
저는 좋아보여서 Approve 할게요!

지금 컨플릭트 나는 것만 해결해주시면 좋을 것 같네요 :)

2024-01-01 08:32 UTC, merged