refactor: Nickname 도메인 모델을 만든다.
fc-online-stats-searching/foss pull request #32
Opened 2023-12-22 14:11 UTC by krrong

## 관련 이슈번호
- closed: #27 

<br/>

## 작업 사항
### Nickname 도메인 모델 생성
도메인 모델을 만들었는데, 현재는 공백만 불가능하도록 해두었습니다. 추후에 피파 닉네임 규정에 맞는 제한을 도메인 모델에 추가하면 좋을 것 같습니다.

### Toast 메시지
**RecentMatchesFragment**  
EditText에 있는 string을 뷰모델로 넘겨주고 뷰모델에서 해당 string을 Nickname 도메인 모델로 바꿉니다. 이 과정에서 exception이 발생하면 event를 Failed로 변경하여 뷰에서 감지하고 토스트를 띄울 수 있도록 했습니다.  

**RelativeStatsFragment**  
EditText에 있는 string을 뷰모델로 넘겨주고 뷰모델에서 해당 string을 Nickname 도메인 모델로 바꾸는 과정까지는 동일합니다.  
하지만 여기서 발생하는 exception을 viewModelScope 밖에서 runCatching으로 잡고있어서 `emit()`을 사용할 수 없더라구요.  
그래서 추후에 UiState를 도입한 뒤에 해당 부분도 처리하면 좋을 것 같다는 생각을 했습니다.

<br/>

## 기타 사항
현재 뷰모델에서 도메인 모델 Nickname을 사용하기 위해 runCatching으로 한 번 감싸주었는데요, 혹시 이보다 더 좋은 방법이 있을까요?  
코드가.. 맘에들지 않습니다.ㅠ

<br/>

2023-12-23 09:30 UTC, boogi-woogi requested changes
정말 고생하셨습니다~ 
lateinit var를 사용하신 부분에서 많은 고민이 느껴집니다!

코멘트 남겼으니 확인해주시면 감사하겠습니다!

2023-12-23 09:30 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +        }.onFailure { }
[P3]
```suggestion
    fun fetchRelativeStats(nickname: String) {
        runCatching {
            viewModelScope.launch {
                relativeStatsRepository.fetchRelativeStats(Nickname(nickname))
                    .onSuccess { relativeStats ->
                        _relativeStats.value = relativeStats.map { it.toUiModel() }
                    }.onFailure {
                        _event.emit(RelativeStatsEvent.Failed)
                    }
            }
            // TODO: UiState로 적용하면서 닉네임 변환 실패 시 처리 필요
        }.onFailure { }
```
lateinit var에 대한 변수를 두지 않고 다음과 같은 형식으로 repository 함수를 호출하는 것은 어떨까요?

2023-12-23 09:30 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
>                  }
[P3]
이 부분도 lateinit var를 사용하지 않고 recyclerView의 아이템으로부터 String 타입의 opponentname, name을 인자로 받아 Nickname 클래스로 wrapping후 사용할 수 있을 것으로 예상되는데 그 방법은 어떠신가요?

2023-12-23 09:30 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
>  }
제가 말한 형식대로 구현이 가능하다면 이러한 함수도 사라질 것으로 예상합니다!

2023-12-27 07:32 UTC, yoonhyeokCho approved these changes
일일이 변경하시느라 귀찮으셨을텐데 고생하셨습니다 !

2023-12-27 07:32 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +        }.onFailure { }
진욱님이 말씀하신 것처럼 fetchRelativeStats 에 실패한 것과 Nickname모델로 변경시 오류를 분기처리 하기 위해서 runCatching으로 감싸는 지금 방법이 제일 좋은 것 같아요.

emit()을 사용할 수 없는 문제 같은 경우에는 말씀하신 것처럼 UiState 도입한 후에 어떻게 처리할지 생각해보죠 !

2023-12-27 07:34 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +        }.onFailure { }
진욱님께서 제시해주신 코드 보면 ViewModelScope 으로 runCatching을 감싸고 있는데, 이러면 fetchRelativeStats()에서 실패를 한 것인지, Nickname 모델로 변경하는데 실패한 것인지 알 수 있나요 ??

2023-12-28 09:42 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
> +        }.onFailure { }
윤혁님이 말해주신 것처럼 runCatching을 외부로 뺀 이유는 `Nickname` 모델로 변경하는데 실패한 것을 나타내기 위함이었습니다.  
어떻게 구현할지는 모르겠지만 제 생각에는 `Nickname`모델로 변경할 때의 실패와 리포지터리에서 받아올 때 실패를 구분하여 처리할 것 같다는 생각을 했어요. 그래서 runCatching이 가장 밖에 있도록 구현한 것입니다!  

혹시 더 좋은 방법이 있을까요?

2023-12-28 09:46 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/statsearching/relative/RelativeStatsViewModel.kt
>                  }
내 닉네임과 상대편의 닉네임 데이터를 함수의 파라미터로 넘겨받고 `fetchRelativeMatchesBetweenUsers`메서드 안에서 `Nickname`모델로 변환하는 것이 어떻냐는 말로 이해했습니다.  

이는 어댑터에서 나의 닉네임을 가지고 있어야 구현이 가능한 방식이라고 생각했습니다.  

이 경우도 고려한 부분 중 하나이긴 하지만 이와 같은 방식으로 구현하게되면 프래그먼트가 액티비티의 뷰모델을 공유할 수 있는 특성을 잘 이용하지 못하는 것이 아닐까 하는 생각이 들었던 것 같아요.  

어떤 방식이 더 나을까요?

2023-12-29 07:16 UTC, boogi-woogi approved these changes
name을 받아오는 방법에 대한 처리는 따로 진행하는 것으로 하고 approve하겠습니다~

2023-12-30 03:58 UTC, merged