refactor: 변수명, 컨벤션 통일 및 di오류 해결
fc-online-stats-searching/foss pull request #35
Opened 2024-01-02 07:16 UTC by boogi-woogi

## 관련 이슈번호
- #34 

## 작업 사항
* 변수명 match, opponentName으로 통일
* di 오류는 아래 코멘트의 방법으로 일단 문제 없이 동작하도록 만듦.

## 기타 사항
https://wool-shame-e88.notion.site/aed44a4d57f74fd996bbfbbda2aa3b10?pvs=4

2024-01-02 07:19 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
>          binding.homeBnvMenu.setOnItemSelectedListener { item ->
일단 이러한 방식으로 di문제가 발생하지 않도록 만들었는데... 양해 부탁드립니다.. 첫 출시 이후 hilt로 변경할게요!

2024-01-02 08:11 UTC, krrong requested changes
전체 파일 확인하면서 컨벤션 맞추는게 보통 일이 아닌데 정말 고생했습니다!  
그래서 저도 꼼꼼히 확인하려고 노력했고 코멘트로 남겨두었습니다!  

그리고 다음과 같은 사항도 확인해주시면 좋을 것 같아요! (꼭 해당 PR에서 해결하지는 않아도 될 것 같습니다.)

1) 앱을 실행하자마자 상대 전적으로 들어가면 앱이 비정상 종료됩니다.

2) 닉네임을 빈 공간으로 두고 검색했을 때 아무런 반응이 없고, 상대 전적으로 이동 했다가 다시 최근 전적으로 돌아왔을 떄 프로그레스 바가 돌아갑니다.

3) 닉네임 검색 후에도 '사용자의 이름을 검색해주세요'라는 문구가 사라지지 않습니다.

2024-01-02 08:38 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/RecentMatchesUiState.kt
> +    data class RecentMatches(val matches: List<MatchUiModel>) : RecentMatchesUiState
음 주관적인 의견이지만 오히려 uiState를 관찰하고 있기 때문에 `성공`이라는 행위에 초점이 맞춰진 이름보다는 어떤 화면을 보여주고 있는지에 대한 이름이 uiState가 현재 어떤 정보들을 담고 있는지에 대해 쉽게 파악할 수 있을 것이라고 생각하는데 조금 더 얘기해보시죠!

2024-01-02 09:30 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/RecentMatchesAdapter.kt
> +class RecentMatchesAdapter : ListAdapter<MatchUiModel, MatchViewHolder>(MatchDiffUtilCallBack()) {
말씀해주신 Match, Matches가 혼용되는 부분들 수정완료했습니다!

2024-01-04 11:55 UTC, yoonhyeokCho approved these changes
고생하셨습니다

2024-01-04 11:55 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/RecentMatchViewModel.kt
> +                    )
StateFlow를 emit하는 것과 value를 사용하는 것의 차이가 뭔가요?

2024-01-08 06:10 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/RecentMatchViewModel.kt
> +                    )
emit은 suspend function 아래의 코드와 같다고 하네요. 비동기적으로 데이터를 갱신하는 상황에서 사용하면 될 것으로 보입니다~
https://stackoverflow.com/questions/66669612/mutablestateflow-difference-between-value-and-emit
```
override suspend fun emit(value: T) {
    this.value = value
}
```

2024-01-08 06:10 UTC, merged