refactor: 상대전적 화면을 uiState로 리팩터링한다.
fc-online-stats-searching/foss pull request #37
Opened 2024-01-09 06:37 UTC by boogi-woogi

## 관련 이슈번호
- #36

## 작업 사항
상대전적 화면을 uiState로 리팩터링
상대전적 item 클릭시 새로운 액티비티로 전환

## 기타 사항
상대전적 클릭시 상세 정보(상대와의 최근전적) 화면을 보여주는 Activity로 전환할 때 이미 리사이클러뷰의 아이템이 해당 가지고 있기 때문에 Parcelable을 이용해 intent로 해당 데이터들을 넘기는 방식으로 구현했습니다!

2024-01-09 08:06 UTC, yoonhyeokCho approved these changes
고생 많으셨습니다 ! 
새로운 방법을 알게 되었네요. 꼼꼼히 확인하고 코멘트 남겼습니다 ~~

2024-01-09 08:06 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/detail/RelativeMatchDetailsActivity.kt
> +    }
[P3]
전환이 이루어지는 액티비티에서 companion object 함수로 만들어서 사용하는 이유가 있나요 ?

2024-01-09 08:06 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/util/ParcelableUtil.kt
> +    }
[P3]
intent로 인스턴스를 전달할 때 Parcelable 사용하는 방법이 있군요 ! 근데 serializable 를 사용하는 방법도 있는 것으로 알고 있는데, 어떤 점에서 Parcelable을 사용하신 걸까요 ?

2024-01-09 14:02 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/util/ParcelableUtil.kt
> +    }
serializable은 reflection을 이용하지만 Parcelable은 reflection을 이용하지 않습니다. 따라서 성능적으로 Parcelable이 좋기는 하지만 개발자가 직렬화 방법을 직접 명시해주어야 한다는 단점이 있습니다. 

하지만 라이브러리를 이용해 Parcelize 어노테이션을 붙이면 직렬화 코드를 자동으로 생성해주기 때문에 그러한 번거로움도 겪지 않을 수 있기 때문에 성능적으로 더욱 뛰어난 Parcelable을 이용했습니다.

2024-01-09 14:05 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/detail/RelativeMatchDetailsActivity.kt
> +    }
A라는 액티비티에서 B라는 액티비티로 전환을 할 때 전환이 이루어지는 내부적인 과정은 A 액티비티의 관심사가 아니라고 생각합니다. 

그래서 개인적으로 이러한 방법을 많이 사용하고는 합니다!

2024-01-09 14:05 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/RelativeMatchViewModel.kt
>                  }
추가하겠습니다~

2024-01-10 05:59 UTC, krrong requested changes
고생하셨습니다!  
앱을 실행하고 사용자를 검색하기 전에 상대 전적으로 이동하면 앱이 비정상 종료되고 있는데 확인해주시면 좋을 것 같습니다!

2024-01-10 05:59 UTC, krrong commented on android/domain/src/main/java/com/foss/foss/model/Match.kt
> +    val opponentName: String,
P[2]  
Nickname을 사용하지 않는다면 도메인 모델이 필요하지 않겠네요.  
함께 삭제하는것도 좋아보입니다!

2024-01-10 05:59 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
> +class HomeActivity : DiActivity() {
P[2]  
OnChangeVisibilityListener 도 사용하지 않는 것 같으니 삭제하는건 어떨까요?

2024-01-10 05:59 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/RelativeMatchFragment.kt
>              }
P[4]  
처리가 깔끔해져서 좋군요!

2024-01-10 05:59 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/RelativeMatchUiState.kt
> +    class RelativeMatches(val relativeMatches: List<RelativeMatchUiModel>) : RelativeMatchUiState
P[3]  
Data Class로 사용해보는 것은 어떤가요?  

현재는 한 번의 요청으로 받아오는 데이터만 가져오면 되지만, 다른 정보도 받아와야 하는 상황으로 변경되면 copy() 메서드를 사용하여 조금 더 간편하게 구현할 수 있을 것 같습니다.


P[2]  
laco-dev님의 [좋은 글](https://medium.com/@laco2951/android-ui-state-modeling-%EC%96%B4%EB%96%A4%EA%B2%8C-%EC%A2%8B%EC%9D%84%EA%B9%8C-7b6232543f25) 하나 남겨보겠습니다.

2024-01-10 05:59 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/detail/RelativeMatchDetailsActivity.kt
> +            context.startActivity(intent)
P[3]  
전환이 이루어지는 내부적인 과정은 A 액티비티의 관심사가 아니라는 것에는 동의합니다.  
하지만 액티비티를 전환하는, 즉 새로운 액티비티를 여는 것은 A액티비티의 관심사라고 생각하는데 이에 대해서는 어떤 생각을 갖고 계신지 궁금합니다.

2024-01-10 05:59 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/RelativeMatchAdapter.kt
> +    private val onClick: (opponentNickname: String, matchDetails: ArrayList<MatchUiModel>) -> Unit
P[4]  
ArrayList를 사용한 특별한 이유가 있나요?

2024-01-10 08:01 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/detail/RelativeMatchDetailsActivity.kt
> +            context.startActivity(intent)
오 말씀해주신 의견에 동의합니다. 그럼 intent까지만 반환하는 것으로하고 startActivity는 Fragment에서 진행하도록 하겠습니다!

2024-01-10 08:02 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/RelativeMatchAdapter.kt
> +    private val onClick: (opponentNickname: String, matchDetails: ArrayList<MatchUiModel>) -> Unit
Parcelable에서는 일반 List를 넘겨주는 메소드가 없어서 다음과 같이 진행했습니다 ㅠㅜ

2024-01-10 08:05 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/relative/RelativeMatchUiState.kt
> +    class RelativeMatches(val relativeMatches: List<RelativeMatchUiModel>) : RelativeMatchUiState
반영하겠습니다!

2024-01-10 12:07 UTC, merged