feat: 최근 전적을 가져오는 기능을 서버와 연결한다.
fc-online-stats-searching/foss pull request #41
Opened 2024-01-12 09:37 UTC by krrong

## 관련 이슈번호
<br/>

## 작업 사항
<br/>

## 기타 사항
<br/>

2024-01-15 08:55 UTC, boogi-woogi requested changes
고생하셨습니다!

작은 코멘트 남겼는데 확인해주시면 감사하겠습니다~

그리고 혹시 브랜치명을 `feature/#38`로 하신 이유가 있으신가요?

> 기본 검색 경기를 전체경기로 고정

스피너는 이미 검색된 결과에 대해서 다시 필터링 해주는 것이 아닌 검색하기 전 받을 데이터의 타입을 설정하는 용도로만 사용해도 괜찮을 것 같은데 어떻게 생각하시나요?

2024-01-15 08:55 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/data/datasource/RecentMatchDataSource.kt
> +            }
[P4]
이러한 부분도 MAPPER로 빼는 것은 어떨까요?

2024-01-15 08:55 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/data/repository/DefaultMatchRepository.kt
> +    }
[P2]
이 부분은 삭제해도 좋을 것 같아요!

2024-01-15 10:02 UTC, yoonhyeokCho approved these changes
고생하셨습니다.

- ### 기본 검색 경기를 전체경기로 고정
전체경기를 기본으로 보여주고, 스피너에서 선택을 하면 이벤트 리스너를 통해서 선택한("공식 경기 or 클래식 경기") matchType으로 다시 요청을 보내 받아온 데이터를 화면에 보여주면 되지 않을까요 ?

- ### 페이지네이션
휴대폰 화면이 크지 않기 때문에 페이지 매김으로 가는 것보단 진욱님이 말씀하신 것처럼 더 보기를 통해서 확장하는 것이 좋을 것 같아요.

2024-01-15 12:44 UTC, krrong commented on android/app/src/main/java/com/foss/foss/data/datasource/RecentMatchDataSource.kt
> +            }
반영했습니다 :)

2024-01-15 12:47 UTC, krrong commented on android/app/src/main/java/com/foss/foss/data/repository/DefaultMatchRepository.kt
> +    }
자세한 경기 결과를 받아오는 방법이 변경되면서 필요없는 메서드가 되었군요! 꼼꼼한 리뷰 감사합니다~

2024-01-15 12:51 UTC, krrong commented
@boogi-woogi 
> 그리고 혹시 브랜치명을 feature/#38로 하신 이유가 있으신가요?

헷갈렸던 것 같습니다.. 🥲 컨벤션 잘 맞추도록 할게요!

<br>

> 스피너는 이미 검색된 결과에 대해서 다시 필터링 해주는 것이 아닌 검색하기 전 받을 데이터의 타입을 설정하는 용도로만 사용해도 괜찮을 것 같은데 어떻게 생각하시나요?

좋은 방법인 것 같습니다. 그렇다면 검색 후에 스피너가 보이도록 하면 예외사항을 줄일 수 있겠네요!

<br>

> op.gg와 같이 더보기 버튼을 클릭해서 페이지네이션 구현해도 좋을 것 같아요~

좋습니다! 해당 내용은 다른 이슈로 연결해서 작업하면 좋을 것 같네요!

<br><br>

@yoonhyeokCho 
> 전체경기를 기본으로 보여주고, 스피너에서 선택을 하면 이벤트 리스너를 통해서 선택한("공식 경기 or 클래식 경기") matchType으로 다시 요청을 보내 받아온 데이터를 화면에 보여주면 되지 않을까요 ?

말씀하신대로 matchType으로 다시 요청을 보내 데이터를 받아 보여주는 것도 좋지만 현재 가지고 있는 데이터를 자체적으로 필터링해서 보여주면 서버에 불필요한 요청을 보내지 않고 더 빠르게 동작할 수 있다고 생각합니다!
진욱님이 남겨주신 것에 대해서는 어떻게 생각하시나요?

<br>

> 휴대폰 화면이 크지 않기 때문에 페이지 매김으로 가는 것보단 진욱님이 말씀하신 것처럼 더 보기를 통해서 확장하는 것이 좋을 것 같아요.

저도 같은 생각입니다! 해당 내용은 다른 이슈로 연결해서 작업하면 좋을 것 같네요!

2024-01-15 13:44 UTC, yoonhyeokCho approved these changes
추가를 해놓고 서밋을 안 했네요,,, !

2024-01-16 08:54 UTC, yoonhyeokCho commented
@krrong 
> 말씀하신대로 matchType으로 다시 요청을 보내 데이터를 받아 보여주는 것도 좋지만 현재 가지고 있는 데이터를 자체적으로 필터링해서 보여주면 서버에 불필요한 요청을 보내지 않고 더 빠르게 동작할 수 있다고 생각합니다!
진욱님이 남겨주신 것에 대해서는 어떻게 생각하시나요?

그러네요. 이미 받아온 데이터에 대해서 또 요청을 보내게 되면 불필요한 요청의 횟수가 많아지겠네요. 진욱님 말씀하신 것처럼 처음에 검색할 때 사용자가 선택한 후에 요청을 보내는 것이 좋을 것 같아요 !

2024-01-16 13:49 UTC, krrong commented on android/app/src/main/java/com/foss/foss/data/mapper/MatchesMapper.kt
> +}
좋은 것 같습니다!  
현재 올라와있는 두 개의 PR중 하나가 머지를 시킨 후 다른 PR에서 공통 유틸로 분리하면 좋을 것 같아요 :)

2024-01-17 12:33 UTC, merged