feat: 상대 전적 관련 기능을 서버와 연결한다.
fc-online-stats-searching/foss pull request #42
Opened 2024-01-13 07:59 UTC by yoonhyeokCho

## 관련 이슈번호
<br/>

#40 
## 작업 사항
<br/>

- woogi-di 적용을 위해 RemoteDataSourceModule 수정
- 상대 전적 관련 DTO, Service, DataSoruce, toDomainModel Mapper, 레포지토리 구현체 구현
## 기타 사항
<br/>

2024-01-13 08:50 UTC, boogi-woogi requested changes
고생하셨습니다!

Dto 혹은 Response를 domain model로 mapping하는 부분은 두 분의 코드가 합쳐졌을 때 다시 한번 보겠습니다!

2024-01-13 08:50 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/data/dto/RelativeMatchDTO.kt
> +)
[P2]
Dto 혹은 Response라는 명칭을 사용하실 예정이라면 모든 클래스에 통일되게 사용해주시면 감사하겠습니다!

2024-01-13 08:50 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/data/datasource/RelativeMatchDataSource.kt
> +        }
[P3]
현재 repository에서도 예외에 대한 catching을 하고 있고 있는데 DataSource에서도 예외를 catching 하는 이유가 궁금합니다. 만약 올바르지 않은 response라면 dataSource에서는 그냥 예외를 throw만 하는 형식으로 구현을 해도 괜찮지 않을까요?

2024-01-13 08:50 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/data/repository/RelativeMatchRepositoryImpl.kt
> +    }
[P3]
runCatching이 아닌 tryCatch를 사용하신 이유가 무엇인가요?
```
runCatching{
        relativeMatchDataSource.fetchRelativeMatches(nickname).map{ it.toDomainModel() }
}
```
다음과 같이 작성해도 기대하는 동작을 할 것 같습니다~

2024-01-15 09:03 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/data/datasource/RelativeMatchDataSource.kt
> +        }
아하 그렇네요. 굳이 두번 처리할 이유가 없군요 !
데이터 소스에서 throw하고, repository에서 처리하는 쪽으로 수정하도록 하겠습니다.

2024-01-15 09:05 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/data/dto/RelativeMatchDTO.kt
> +)
넵 수정하겠습니다

2024-01-15 12:38 UTC, krrong requested changes
고생하셨습니다!  
현재 앱을 실행해보면 승률에 따라 왼쪽바의 색이 변하지 않고있는데, 확인해주시면 좋을 것 같습니다.

2024-01-15 12:38 UTC, krrong commented on android/app/src/main/java/com/foss/foss/data/dto/RelativeMatchesDTO.kt
> +data class RelativeMatchesDTO(
P[4]  
Dto 클래스를 다른 파일로 구분하지 않은 이유가 있으신가요?

2024-01-15 12:38 UTC, krrong commented on android/app/src/main/java/com/foss/foss/data/mapper/RelativeMatchDtoMapper.kt
> +
P[3]
```kotlin
return List(win) { WinDrawLose.Win } + List(tie) { WinDrawLose.Draw } + List(lose) { WinDrawLose.Lose }
```

이렇게 작성하면 더 깔끔하게 보일 수도 있겠네요!

2024-01-15 12:38 UTC, krrong commented on android/app/src/main/java/com/foss/foss/data/repository/RelativeMatchRepositoryImpl.kt
> +class RelativeMatchRepositoryImpl(
P[3]  
저는 Repository 인터페이스의 구현체 이름을 Default* 로 짓는 것을 선호하는데 윤혁님은 Default* 과 *Impl 중 어떤 것이 더 끌리시나요?

2024-01-15 12:38 UTC, krrong commented on android/app/src/main/java/com/foss/foss/data/FakeRelativeMatchRepository.kt
> +// class FakeRelativeMatchRepository : RelativeMatchRepository {
P[2]  
앞으로 사용하지 않을 클래스처럼 보여 삭제해도 괜찮을 것 같아요!

2024-01-15 12:38 UTC, krrong commented on android/app/src/main/java/com/foss/foss/data/mapper/RelativeMatchDtoMapper.kt
> +        manOfTheMatch = 1,
P[3]  
상대 전적을 자세한 뷰로 들어가서 보게되면 결국 MOM을 보여줘야 하기 때문에 Match로 변환하는 과정에서 MOM을 계산하는 것이 좋지 않을까 생각하는데 어떻게 생각하시나요?

2024-01-15 13:26 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/data/dto/RelativeMatchesDTO.kt
> +data class RelativeMatchesDTO(
데이터 타입이 많지 않다고 생각을 해서 한 파일로 정리하는 것이 가독성이 좋다고 판단했습니다.

2024-01-15 13:27 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/data/mapper/RelativeMatchDtoMapper.kt
> +
아하 ! 그렇게 하는 방법이 있네요 ! 반영하도록 하겠습니다.

2024-01-15 13:28 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/data/repository/RelativeMatchRepositoryImpl.kt
> +class RelativeMatchRepositoryImpl(
저는 주로 구현체의 이름을 Impl 했었는데, 생각해보니 저희 파일명 통일을 할때 구현체는 Default로 하자고 했던 것 같네요
제가 수정하도록 하겠습니다 !

2024-01-15 13:28 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/data/FakeRelativeMatchRepository.kt
> +// class FakeRelativeMatchRepository : RelativeMatchRepository {
넵 반영하도록 하겠습니다.

2024-01-15 13:49 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/data/mapper/RelativeMatchDtoMapper.kt
> +        manOfTheMatch = 1,
네 맞습니다 말씀해주신 것처럼 Match로 변환을 할 때 MOM을 구하려고 했었는데 , 임시로 값을 대입해놓고 구현을 안 해놓았네요
추가해서 올리도록 하겠습니다 !

2024-01-18 07:37 UTC, boogi-woogi approved these changes
고생하셨습니다~

2024-01-18 11:40 UTC, krrong requested changes
충돌이 정말 많았을 것 같은데 해결하시느라 고생하셨습니다!

2024-01-18 11:40 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
>      }
[P2]  
어떤 작업을 위한 코드일까요? 해당 코드가 있는 상태로 앱을 실행시켰을 때 스피너를 자세히 보면 아래방향 화살표가 2개인 것을 확인할 수 있습니다.

2024-01-18 11:48 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/home/HomeActivity.kt
>      }
![image](https://github.com/fc-online-stats-searching/foss/assets/88770426/40a56dc9-4f54-4525-9f7a-3892dc6fa71c)
이 상태에서 선택된 클래식 1on1에만 화살표가 보이는 textView를 만들기 위해서 추가한 코드입니다!
spinner에 크기를 지정함으로써 해결했습니다~

2024-01-18 12:16 UTC, merged