feat: 메인 페이지를 만든다.
fc-online-stats-searching/foss pull request #48
Opened 2024-02-19 09:06 UTC by boogi-woogi

## 관련 이슈번호
- #47 

## 작업 사항
* 컴포즈로 메인 페이지를 개발했습니다.
* figma에 정의된 폰트와 colorResource들을 모두 추가해놓았습니다.
<br/>

## 기타 사항
![image](https://github.com/fc-online-stats-searching/foss/assets/88770426/f5992815-3387-4265-8ac5-32bc4adbe39f)
![image](https://github.com/fc-online-stats-searching/foss/assets/88770426/edec7b6e-e87d-4af2-91da-2b6c1246d1ad)
현재 기기에 따라서 일그러지는 경우도 있는데 이것은 추후에 반응형으로 해결해야할 듯 합니다!
<br/>

2024-02-19 09:08 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/util/FontUtil.kt
> +)
사용되는 font들을 사용할 수 있도록 fontFamily를 가져올 수 있는 함수를 만들었습니다.
추후에 Theme을 사용할 때는 Theme.kt에서 같은 설정을 기본적으로 설정할 수 있는 것으로 알고있습니다!

2024-02-19 09:08 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/main/MainScreen.kt
> +        text = stringResource(R.string.main_menu_search)
현재는 이와같이 fontFamily를 설정하여 Text코드 작성해주시면 감사하겠습니다!

2024-02-19 09:11 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/main/MainScreen.kt
> +}
화면 이동로직을 MainNavigationButton의 마지막에 주입해주시면 됩니다!
(이동할 Activity를 일단 임시로 만들어두었습니다.)

2024-02-23 06:49 UTC, krrong requested changes
고생했습니다! 덕분에 컴포즈에 대해 많이 배웠습니다 :)

2024-02-23 06:50 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/main/MainScreen.kt
> +        text = stringResource(R.string.main_menu_search)
좋은 것 같습니다 :)

2024-02-27 07:10 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/main/MainScreen.kt
> +            ),
아하 이해했습니다! 코드랩 포함 여러 코드 베이스들이 modifier를 주입받는 형태이다보니 아직까지 어떨 때 새로운 Modifier를 선언해야하는지 판단이 잘 서질 않는 것 같아요

2024-02-27 11:43 UTC, yoonhyeokCho approved these changes
컴포즈 공부하면서 수정하느라 힘드셨을 것 같아요

전반적으로 가독성도 좋고, 구조가 명확하게 보여서 좋네요 !
홈 화면 잘 만들어 주셔서 다른 화면 작업을 할 때 수월하게 할 수 있을 것 같아요 

고생하셨습니다

2024-02-27 11:43 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/main/MainScreen.kt
> +        text = stringResource(R.string.main_menu_search)
어떻게 하든 괜찮아요

그런데 위와 같은 방식으로 하는 것이 Theme를 사용하는 방법에 비해 장 단점이 있나요 ?

2024-02-27 11:43 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/util/FontUtil.kt
> +)
넵 ! 상세한 설명 감사합니다

2024-02-27 11:43 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/main/MainScreen.kt
> +) {
재사용할 수 있는 컴포넌트들은 MainScrenn.kt 파일에서 한번에 관리하는 것보다 , 따로 관리를 하는게 낫지 않을까요 ?

2024-02-27 11:48 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/main/MainScreen.kt
> +        text = stringResource(R.string.main_menu_search)
어떻게 하든 상관없을 것 같은데,, Theme를 사용한 방법과 위 방법간의 장 단점이 있나요 ?

2024-02-29 04:33 UTC, merged