feat: 최근 전적 뷰를 구성한다.
fc-online-stats-searching/foss pull request #51
Opened 2024-02-27 11:38 UTC by krrong

## 관련 이슈번호
- closed: #49 
<br/>

## 작업 사항
- 최근 전적 뷰를 최대한 피그마와 비슷하게 컴포즈로 구현했습니다.

<br/>

## 기타 사항
- `TextField`에 아이디를 입력하고, 검색하는 기능은 추가하지 않았습니다.
- 새로고침 아이콘을 클릭했을 때의 동작을 정의해주지 않았습니다.
- 날짜별로 탭을 새로 만드는 뷰를 구현하지 않았습니다.
- 경기가 몇분동안 진행되었는지는 서버에서 전달받는 데이터가 아니기 때문에 상수로 "08:00"의 형태로 지정해두었습니다.
- 피그마를 보면 경기 [타입 / 몇분전] 뷰가 우측 상단에 존재하는데, 그렇게 구현하는 것이 조금 까다로워서 일단 중앙에 배치해두었습니다.

<br/>

## Recording
[recording.webm](https://github.com/fc-online-stats-searching/foss/assets/84285337/d7e42490-8cce-4b18-98bf-9005a45f6790)

2024-02-28 05:27 UTC, boogi-woogi requested changes
구현하시느라 고생하셨습니다ㅎㅎ 저도 아직까지 컴포즈에 대한 많은 지식이 없어서 어떤 코멘트를 남겨야 할 지 잘 모르겠네요 ㅠ

현재 경기 수에 따라 LazyColumn의 height가 변화하여 아래 배경이 흰색이 나오는 현상이 있는데 수정해주시면 감사하겠습니다ㅎㅎ
![image](https://github.com/fc-online-stats-searching/foss/assets/88770426/d01a4dff-87ee-4b99-b97d-48b430871ce1)

2024-02-28 05:27 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +    }
[P4]
이러한 로직들도 뭔가 분리가 되면 좋을 것 같은데 어떻게 생각하시나요?

2024-02-28 05:27 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +            },
[P3]
strings.xml로 분리하면 좋을 것 같아요ㅎㅎ

2024-02-28 05:27 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +                },
아직까지 구현이 되지 않은 부분이라 이렇게 놔두신 것 같아요. 
나중의 테스트를 위해 onClick과 같은 로직은 미리 주입받는 형태로 만들어주시면 감사하겠습니다ㅎㅎ

2024-02-28 05:27 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +        leadingIcon = {
동일하게  `onValueChange()`도 같은 맥락이라고 생각됩니다ㅎㅎ

2024-02-29 04:31 UTC, yoonhyeokCho approved these changes
고생하셨습니다 

컴포즈 공부하면서 하시느라 애 많이 쓰셨을 것 같아요 ! 
잘 참고해서 다음 부분 완성하도록 하겠습니다

2024-03-05 13:02 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +            },
반영했습니다!

2024-03-05 13:08 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +                },
반영했습니다 :)

2024-03-05 13:18 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +        leadingIcon = {
반영했습니다 :)

2024-03-05 13:20 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +            )
저도 코드랩을 보면서 학습하고 있기 때문에 맞는 이야기인지는 모르겠습니다만 제 생각은 다음과 같습니다.  
컴포저블 함수를 감싸는 최상위 컴포저블 함수의 modifier는 인자로 받아온 modifier를 전해주고, 하위에 생성하는 새로운 컴포넌트 함수들은 새로운 Modifier를 생성하여 추가합니다.  


이렇게 진행하는 이유는 기본적으로 컴포저블 함수는 외부에서 modifier를 인자로 넘겨줌으로써 해당 컴포저블 함수를 어떤 형태로 그리겠다라고 이야기를 하는데요, 만약 넘어온 modifier를 하위 컴포넌트 함수에 넘겨주면 예상과는 다른 동작이 가능하기 때문입니다.

2024-03-05 13:22 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +    )
오 이것도 가독성을 높일 수 있는 좋은 방법인 것 같네요! 감사합니다 :)

2024-03-07 05:45 UTC, krrong commented on android/app/src/main/java/com/foss/foss/feature/matchsearching/recent/NewRecentMatchActivity.kt
> +    }
반영했습니다!

2024-03-08 11:01 UTC, merged