Feat/53
fc-online-stats-searching/foss pull request #54
Opened 2024-02-29 13:28 UTC by yoonhyeokCho

## 관련 이슈번호
<br/>

#53 

## 작업 사항
<br/>

Jetpack Compose를 활용하여 상대 전적 뷰 구성
<img width="498" alt="image" src="https://github.com/fc-online-stats-searching/foss/assets/90389363/541260c2-769a-4748-a1f1-040dfd2abfa4">

## 기타 사항
<br/>

- 우선 임시 데이터를 만들어서 뷰를 구성했습니다. 
- 티어 관련 이미지 figma에는 있던데, 초기에 저희 티어 관련 이미지 관련해서 없애기로 한 것 같은데 관련해서 얘기 해봐야 할 것 같습니다.
- 디테일 ( > ) 클릭 시 다음 화면 어디로 연결할지 얘기해보면 좋을 것 같습니다 !

2024-03-02 09:41 UTC, boogi-woogi requested changes
Navigation까지 적용하신 것 잘 보았습니다~ 

작성해주신 것처럼 Activity여러 개가 아닌 하나의 액티비티를 구성해서 Screen을 navigation을 이용해 화면 이동이 되도록 추후에 리팩터링이 필요할 것 같네요ㅎㅎ

그리고 주관적인 생각이지만 티어 정보는 서버쪽이랑 얘기해서 다시 추가하는 것이 좋을 것 같아요!

2024-03-02 09:41 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchActivity.kt
> +        super.onCreate(savedInstanceState)
이건 제가 임시로 이름이라 바꾸셔도 됩니다!

2024-03-02 09:41 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchScreen.kt
> +    }
[P3]
이런 로직은 또 다른 함수로 분리할 수 있을 것 같아요

2024-03-02 09:41 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchScreen.kt
> +) {
이런 것도 주입받을 수 있군요 ㄷ ㄷ

2024-03-02 09:41 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchActivity.kt
> +    }
사실 제가 처음 구성할때 화면을 Activity 여러개로 구성하는 것이 아닌 작성해주신 것처럼 Navigation을 이용했어야하는데 추후에 리팩터링이 필요할 것 같네요

2024-03-02 09:41 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchActivity.kt
> +        }
[P3]
이것 전체를 ~~~Screen으로 분리하는 것에 대해서는 어떻게 생각하시나요?

2024-03-02 09:41 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchScreen.kt
> +    var text by remember { mutableStateOf("") }
[P4]
추후에 테스트를 위해서는 textString도 주입 받을 필요가 있어보입니다!

2024-03-04 05:07 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchActivity.kt
> +        super.onCreate(savedInstanceState)
그럼 그냥 RelativeMatchActivity 로 하는게 좋을까요 ??

2024-03-04 05:07 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchScreen.kt
> +    }
저 부분은 임시데이터를 사용하기 위해서 해놓은거라 추후에 삭제할 예정입니다 ㅎㅎ

2024-03-04 05:08 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchScreen.kt
> +) {
저도 검색하면서 알게되었습니다.. ! ㅋㅋㅋ

2024-03-04 05:09 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchActivity.kt
> +        }
괜찮은 것 같습니다. 저도 아직 감이 안 와서 우선은 한 곳에다가 다 만들었는데, 어디까지 따로 분리를 해야할지 모르겠네요 ㅠㅠ

2024-03-04 07:23 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/relativematch/NewRelativeMatchActivity.kt
> +        super.onCreate(savedInstanceState)
음 그게 좋아보이긴하는데 현재 이미 해당 액티비티가 존재하니까 navigation 사용하는 구조로 만들면서 리팩터링해도 좋을것 같아요

2024-03-10 09:35 UTC, merged