refactor: 협의한 Navigation 구조로 화면 이동 로직을 통일시킨다.
fc-online-stats-searching/foss pull request #65
Opened 2024-03-15 05:59 UTC by yoonhyeokCho

## 관련 이슈번호
<br/>

- #62 

## 작업 사항
<br/>

- 상대 전적, 최근 전적의 Navigation 적용했습니다.
- 상대 전적, 최근 전적에 있는 `TopBar` 를 별도의 컴포저블 함수로 분리했습니다.

## 기타 사항
<br/>

- 상대 전적 화면에서 아이템 클릭(`onRelativeMatchClick`) 시 다음 화면이 피그마 상에서는 최근 전적 화면과 동일하던데 어떻게 하면 될까요 ?

2024-03-15 14:09 UTC, boogi-woogi requested changes
고생하셨습니다! 그런데 ViewModel이 연결될 것을 대비해서 아래의 코드를 한번 참고해주시면 감사하겠습니다~
https://github.com/wisemuji/DroidKnights2023_App/blob/main/feature/contributor/src/main/java/com/droidknights/app2023/feature/contributor/ContributorScreen.kt

2024-03-15 14:09 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/design/component/Topbar.kt
> +                style = FossTheme.typography.title01,
[P4]
그냥 TopBar라는 명칭보다 Foss내부에서 사용되는 TopBar라는 것을 나타내기 위해서 `FossTopBar()`라는 명칭은 어떠신가요? 공통적으로 사용되는 다른 design component도 `FossXXX`라는 명칭을 가지면 더욱 읽기 쉬울 것 같아요

2024-03-15 14:09 UTC, boogi-woogi commented on android/app/src/main/java/com/foss/foss/feature/home/navigation/RelativeMatchNavigation.kt
> +}
[P3]
현재의 구조에서는 viewModel이 연결되어 있지 않아 Screen 호출이 충분하다고 생각하지만 viewModel이 연결되기 위해서 `XXXRoute()`라는 함수를 만들기도 하더라구요 참고하시구 이 구조로도 한번 생각해주시면 감사하겠습니다~
https://github.com/wisemuji/DroidKnights2023_App/blob/main/feature/contributor/src/main/java/com/droidknights/app2023/feature/contributor/ContributorScreen.kt

2024-03-17 11:08 UTC, krrong approved these changes
고생하셨습니다!  
실제로 앱을 실행시켜보니 예쁘네요 :)  
진욱님이 남겨주신 리뷰만 확인해주시면 좋을 것 같습니다!

2024-03-18 06:25 UTC, yoonhyeokCho commented on android/app/src/main/java/com/foss/foss/design/component/Topbar.kt
> +                style = FossTheme.typography.title01,
넵 그게 좋을 것 같네요 반영하도록 하겠습니다 !

2024-03-18 08:07 UTC, merged